apiVersion: logging.pf9.io/v1alpha1
kind: Output
metadata:
  name: es-object
spec:
  type: elasticsearch
  params:
    - name: url
      value: http://elasticsearch.logging.svc.cluster.local:9200 
    - name: user
      value: test-elastic
    - name: password
      value: test-password
    - name: index_name
      value: test-index