apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: filters.logging.pf9.io
spec:
  group: logging.pf9.io
  names:
    kind: Filter
    listKind: FilterList
    plural: filters
    singular: filter
  scope: Namespaced
  version: v1alpha1
