apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sources.logging.pf9.io
spec:
  group: logging.pf9.io
  names:
    kind: Source
    listKind: SourceList
    plural: sources
    singular: source
  scope: Namespaced
  version: v1alpha1
