apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluentd-operator
  template:
    metadata:
      labels:
        name: fluentd-operator
    spec:
      serviceAccountName: fluentd-operator
      containers:
        - name: fluentd-operator
          # Replace this with the built image name
          image: platform9/fluentd-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - /fluentd/bin/fluentd-operator
          - -cfg-dir
          - /fluentd/etc/conf
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "fluentd-operator"
