kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-operator
subjects:
- kind: ServiceAccount
  name: fluentd-operator
roleRef:
  kind: Role
  name: fluentd-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-operator-deployer
subjects:
- kind: ServiceAccount
  name: fluentd-operator
  namespace: pf9-operators
roleRef:
  kind: ClusterRole
  name: fluentd-operator-deployer
  apiGroup: rbac.authorization.k8s.io