apiVersion: logging.pf9.io/v1alpha1
kind: Output
metadata:
  name: loki-object
spec:
  type: loki
  params:
    - name: url
      value: http://loki.default.svc.cluster.local:3100
    - name: extra_labels
      value: '{"env": "pf9-log"}'
    - name: flush_interval
      value: 1s
    - name: buffer_chunk_limit
      value: 1m
